// <auto-generated />
using BeforeIDie.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BeforeIDie.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201009125015_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("BeforeIDie.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("GoalItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wielki Kanion Kolorado",
                            ImgUrl = "https://goryiludzie.pl/sites/default/files/atoms/image/2016/12/15/1280px-grand_canyon_march_2013.jpg",
                            Localization = "Arizona USA",
                            Title = "Wielki Kanion Kolorado"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zorza Polarna",
                            ImgUrl = "https://cdn.pixabay.com/photo/2018/10/14/20/17/aurora-3747376_1280.jpg",
                            Localization = "Biegun Północny",
                            Title = "Zorza Polarna"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Koloseum",
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d8/Colosseum_in_Rome-April_2007-1-_copie_2B.jpg",
                            Localization = "Rzym, Włochy",
                            Title = "Koloseum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
