// <auto-generated />
using System;
using BeforeIDie.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BeforeIDie.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("BeforeIDie.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("DateOfRealization")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feelings")
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("GoalItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfRealization = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "przełom rzeki Kolorado w stanie Arizona w USA przez Płaskowyż Kolorado. Za początek kanionu uznaje się Lee's Ferry (niewielka stacja z motelem i przystanią dla łodzi leżąca około 12 km od miejscowości Page), natomiast koniec kanionu leży w rejonie Grand Wash Cliff leżącym około 20 km od początku jeziora Mead[1]. Odległość pomiędzy tymi punktami mierzona nurtem rzeki Kolorado wynosi 446 km[1]. Najgłębszym rejonem Wielkiego Kanionu jest Granite Gorge (Wąwóz Granitowy)[2], w którym najgłębsze miejsce leży poniżej krawędzi o 1857 m (6093 stóp)[3]. Szerokość kanionu waha się od ok. 800 m (pod punktem widokowym Toroweap na North Rim – Północnej Krawędzi) do 29 km w najszerszym miejscu. Jest to największy przełom rzeki na świecie (jednak nie najgłębszy).",
                            ImgUrl = "https://goryiludzie.pl/sites/default/files/atoms/image/2016/12/15/1280px-grand_canyon_march_2013.jpg",
                            Localization = "Arizona USA",
                            Rating = 0,
                            Status = 0,
                            Title = "Wielki Kanion Kolorado"
                        },
                        new
                        {
                            Id = 2,
                            DateOfRealization = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Na Ziemi zorze występują na wysokich szerokościach geograficznych, głównie za kołami podbiegunowymi, chociaż w sprzyjających warunkach bywają widoczne nawet w okolicach 50. równoleżnika. Zdarza się, że zorze polarne obserwowane są nawet w krajach śródziemnomorskich. Na półkuli północnej zorza jest określana łacińską nazwą Aurora borealis, a południowa zorza polarna nosi nazwę Aurora australis.",
                            ImgUrl = "https://cdn.pixabay.com/photo/2018/10/14/20/17/aurora-3747376_1280.jpg",
                            Localization = "Biegun Północny",
                            Rating = 0,
                            Status = 0,
                            Title = "Zorza Polarna"
                        },
                        new
                        {
                            Id = 3,
                            DateOfRealization = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amfiteatr Flawiuszów jest najbardziej znanym symbolem Wiecznego Miasta i zarazem jedną z najwspanialszych budowli antycznych, które dotrwały do naszych czasów. Jest on doskonałym świadectwem wielkiego poziomu architektury i budownictwa Imperium Rzymskiego.",
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d8/Colosseum_in_Rome-April_2007-1-_copie_2B.jpg",
                            Localization = "Rzym, Włochy",
                            Rating = 0,
                            Status = 0,
                            Title = "Koloseum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
